### ISSUE TITLE
Getting Merge Trees Error.

### ISSUE THREAD

**Issue by jackmatt2** [altrim/ember-cli-tooltipster#19] opened 2016-05-13 01:04 UTC
Getting the following error, I am using SASS also in my project, maybe that is why.

```
version: 2.4.2
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: Merge error: file app/styles/app.scss exists in /Users/jack/git/my-project/tmp/broccoli_merge_trees-input_base_path-baeLMgXN.tmp/23 and /Users/jack/git/my-project/tmp/broccoli_merge_trees-input_base_path-baeLMgXN.tmp/49
```

**Comment by altrim** [comment] 2016-05-14 10:52
@jackmatt2 Can you provide more information or a repo to reproduce the issue? I am using SASS as well and it should work with that.

**Comment by jackmatt2** [comment] 2016-05-14 11:24
The reason for this is that `/app/styles/app.scss` exists in the app namespace.  The problem is that everything in the `app` namespace in merged into the consuming application as though it were defined there (this is not true for the `addon` namespace).  Therefore, as I already have an `app.scss` file in my project, broccoli does not know which one to use. Deleting `/app/styles/app.scss` from this addon will solve the issue for anyone using sass in their consuming project.

**Comment by altrim** [comment] 2016-05-14 11:35
I was aware of this issue since last year and thought that has already been fixed by ember-cli. Looking through some other similar issues looks like this is still a problem. I will delete delete `/app/styles/app.scss` and release a new version later today. Thanks for the help.

**Closed** 2016-05-14 17:10 UTC
